export const projects = [
  {
    id: 'blackwall',
    code: 'PRJ_001',
    name: 'PROJECT BLACKWALL',
    slug: 'blackwall',
    year: '2024',
    tags: ['C', 'RUST', 'EBPF', 'PYTORCH'],
    category: 'AUTONOMOUS_DEFENCE',
    tagline: 'Autonomous cyber defence. Four interdependent pillars.',
    description: 'Framework: Sentinel (C/eBPF/XDP), Void (Rust/Firecracker deception), Brain (PyTorch LSTM anomaly), Vault (post-quantum crypto). Minimal human intervention.',
    link: 'https://github.com/humm3ll/blackwall',
  },
  {
    id: 'bininspect',
    code: 'PRJ_002',
    name: 'BININSPECT',
    slug: 'bininspect',
    year: '2024',
    tags: ['C++', 'ELF', 'SECURITY'],
    category: 'SECURITY_TOOLING',
    tagline: 'ELF binary structural analysis and validation.',
    description: 'CLI tool for analysing and validating ELF binary integrity. Built for malware triage, exploit research, and secure engineering workflows.',
    link: 'https://github.com/humm3ll/BinInspect',
  },
  {
    id: 'lunarlander',
    code: 'PRJ_003',
    name: 'LUNARLANDER RL',
    slug: 'lunarlander',
    year: '2024',
    tags: ['PYTHON', 'RL', 'PYTORCH'],
    category: 'MACHINE_LEARNING',
    tagline: 'Deep RL algorithm comparison. Graded 90/100.',
    description: 'Comparative analysis of DQN, DDQN, and Dueling DQN on LunarLander-v3 (OpenAI Gymnasium). Assessed for CIS2719.',
    link: 'https://github.com/humm3ll/LunarLander-v3-RL',
  },
  {
    id: 'rockyou',
    code: 'PRJ_004',
    name: 'ROCKYOU ANALYSIS',
    slug: 'rockyou',
    year: '2024',
    tags: ['PYTHON', 'ML', 'DATA_SCI'],
    category: 'DATA_SCIENCE',
    tagline: 'EDA + ML on the RockYou password dataset.',
    description: 'ML comparison (LR, RF, SVM) on RockYou. Critical evaluation of inflated classifier metrics in password security contexts.',
    link: 'https://github.com/humm3ll/RockYouAnalysis',
  },
]

export const bootLines = [
  'INITIALISING SYSTEM...',
  'LOADING KERNEL MODULES...',
  'ESTABLISHING SECURE CHANNEL...',
  'BYPASSING FIREWALL [OK]',
  'DECRYPTING IDENTITY FILE...',
  'AUTH: HULME_E // CLEARANCE_LVL_02',
  'DEPLOYING PORTFOLIO_SYS v2.0',
  'ALL SYSTEMS NOMINAL.',
  '> WELCOME.',
]
