export const projects = [
  {
    id: 'blackwall',
    pid: 'PRJ_001',
    index: '01',
    name: 'Project Blackwall',
    year: '2024',
    tags: ['C', 'Rust', 'eBPF', 'PyTorch'],
    category: 'Autonomous Defence',
    span: 'wide',   // 60%
    short: 'Autonomous cyber defence operating across four interdependent pillars.',
    description: 'An autonomous cyber defence framework: Sentinel (C/eBPF/XDP network threat detection), Void (Rust/Firecracker deception layer), Brain (PyTorch LSTM anomaly engine), Vault (post-quantum cryptography). Minimal human intervention required.',
    link: 'https://github.com/humm3ll/blackwall',
    accent: '#c8ff00',
  },
  {
    id: 'bininspect',
    pid: 'PRJ_002',
    index: '02',
    name: 'BinInspect',
    year: '2024',
    tags: ['C++', 'ELF', 'Security'],
    category: 'Security Tooling',
    span: 'narrow', // 40%
    short: 'C++ CLI for ELF binary structural analysis and integrity validation.',
    description: 'Security-focused command-line tool for analysing ELF binary structural integrity. Built for malware triage, exploit research, and secure engineering workflows.',
    link: 'https://github.com/humm3ll/BinInspect',
    accent: '#d4d4d4',
  },
  {
    id: 'lunarlander',
    pid: 'PRJ_003',
    index: '03',
    name: 'LunarLander RL',
    year: '2024',
    tags: ['Python', 'RL', 'PyTorch'],
    category: 'Machine Learning',
    span: 'narrow',
    short: 'Deep RL algorithm comparison in OpenAI Gymnasium. Graded 90/100.',
    description: 'Comparative analysis of DQN, DDQN, and Dueling DQN applied to LunarLander-v3. Assessed for CIS2719, graded 90/100.',
    link: 'https://github.com/humm3ll/LunarLander-v3-RL',
    accent: '#d4d4d4',
  },
  {
    id: 'rockyou',
    pid: 'PRJ_004',
    index: '04',
    name: 'RockYou Analysis',
    year: '2024',
    tags: ['Python', 'ML', 'Data Science'],
    category: 'Data Science',
    span: 'wide',
    short: 'EDA and ML model comparison on the RockYou password dataset.',
    description: 'EDA and ML comparison (LR, RF, SVM) on the RockYou dataset. Includes critical evaluation of inflated classifier metrics in password security contexts.',
    link: 'https://github.com/humm3ll/RockYouAnalysis',
    accent: '#c8ff00',
  },
]

export const skills = [
  { name: 'Python',       note: 'Scripting · ML · Analysis' },
  { name: 'C / C++',      note: 'Systems · Security' },
  { name: 'Rust',         note: 'Low-level · Safe Systems' },
  { name: 'Bash / Linux', note: 'Kali · Arch · Automation' },
  { name: 'PyTorch',      note: 'ML · RL · LSTM' },
  { name: 'Java',         note: 'OOP · Coursework' },
  { name: 'SQL',          note: 'Data · Backends' },
]
